### PR TITLE
[CLOUD-2192] new version of datasources.env, hibernate-portfolio-vdb.xml, jdg-mat-cache-vdb.xml

### PR DESCRIPTION
**Pull request by penehyba**
datasources.env row
`if [ -f "/deployments/jdg-remote-cache-mat-vdb.xml" ]; then`
changed to:
`if [ -f "/deployments/jdg-mat-cache-vdb.xml" ]; then  `
added:
MAT_CACHE_PROPERTY_UserName=jdg
MAT_CACHE_PROPERTY_Password=JBoss.123
MAT_CACHE_PROPERTY_AuthenticationRealm=ApplicationRealm
MAT_CACHE_PROPERTY_AuthenticationServerName=jdg-server
MAT_CACHE_PROPERTY_SaslMechanism=DIGEST-MD5

jdg-mat-cache-vdb.xml:
fixed st_stockCache -> ST_stockCache
added primary key

hibernate-portfolio-vdb.xml
added primary key

### CODE REVIEW

**Comment by rcernich** [comment]
could we get these squashed and add a jira id to the message (for tracking purposes).  TIA

**Comment by vhalbert** [comment]
I thought we were not worrying about that, so that we could get to a base line for 6.4

**Comment by rcernich** [comment]
Right, but don't we have a general "create jdv 6.4 image" jira?

**Comment by vhalbert** [comment]
yes, its CLOUD-2067
However, these changes are for the quickstart.

**Comment by maschmid** [comment]
I have added this PR to teh https://issues.jboss.org/browse/CLOUD-2192

**Comment by rcernich** [comment]
In the future, please use a working branch for your changes.  I manually processed the PR to ensure your master branch would stay in sync with upstream master.

**Pull request merged**
