### PR TITLE
[CLOUD-450] - Get hellorules-client working within OpenShift

### PR DESCRIPTION
**Pull request by spolti**

### CODE REVIEW

**Comment by rcernich** [comment]
@spolti, can you please add a readme that describes how to instantiate the client using one of the eap templates (presumably, the eap64-basic-s2i template)?

**Comment by spolti** [comment]
Hey @rcernich, sure thing.

**Comment by rcernich** [comment]
I think we need to be careful using new-app with references to application-templates master branch.  The master branch will be changing as we evolve.  Is there a way to document how to do this using the web UI instead?

Also, I don't remember whether or not the client provided a web application, but, if so, can you access it and does it correctly access the rules engine?

**Comment by spolti** [comment]
Hey @rcernich , I'll take a look on this.

**Pull request merged**
