### PR TITLE
Upgrade kie version

### PR DESCRIPTION
**Pull request by spolti**
Upgrade the kie server to use the quickstarts with the new rhdm kie-server image.

### CODE REVIEW

**Comment by rcernich** [comment]
Will this prevent the quickstarts from being used by the 6.4 images?  I'm not sure if the templates reference master or not, but this is something to be cognizant of.

**Comment by spolti** [comment]
The templates use the branch 1.3.
I think we could create a new branch, i.e 1.4 to use with bxms 7.

**Comment by rcernich** [comment]
Another option would be to collocate these with the image source, so it can evolve with the image independently of any other images.

**Comment by spolti** [comment]
Sounds good, but, wouldn't it duplicate the quickstart or the plan is to remove it from jboss-openshift org?

**Pull request closed without merging**
